default={"layers":[2,2,2,2],
        "epochs":100,
        "batch_size":40,
        "verbose_step":100,
        "momentum":0.9,
        "lr":0.001,
        "log_dir":"./tboard",
        "ckpts_dir":"./ckpts",
        "mode":"train"}
