hydra:
  run:
    dir: ./output/${now:%Y-%m-%d}/${now:%H-%M-%S}

parameters:
  layers: [2,2,2,2]
  epochs: 10
  batch_size: 40
  verbose_step: 100
  verbose: 1
  momentum: 0.9
  lr: 0.001
  mode: "train"
  log_dir: "./tboard"
  ckpts_dir: "./ckpts"
  block: "basic"
  num_classes: 10
  model: "resnet18"
